name: Deploy EC2 instance 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print my name
        run: |
          echo "poovarasan"
          echo "valga"

      - name: current folder
        run: |
          pwd
