name: Deploy EC2 instance 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  release:
    types:
      - published
      - created
      - prereleased
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: print my name
        run: |
          echo "poovarasan"
          echo "valga"

      - name: current folder
        run: |
          pwd
